# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dcp < Formula
  desc "Nexqloud DCP CLI"
  homepage "https://nexqloud.io"
  version "1.0.6"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://cli.dcp.nexqloud.net/latest/dcp_1.0.6_darwin_amd64.tar.gz"
      sha256 "71ab80dc41b09254576f604e31807129c3b85e41f7def6bd762b99ce900c2cbb"

      define_method(:install) do
        bin.install "dcp"
      end
    end
    if Hardware::CPU.arm?
      url "https://cli.dcp.nexqloud.net/latest/dcp_1.0.6_darwin_arm64.tar.gz"
      sha256 "a6c08f513368248de678c3c0ecc472c23edde94b000dd2e94c87f418811efd81"

      define_method(:install) do
        bin.install "dcp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://cli.dcp.nexqloud.net/latest/dcp_1.0.6_linux_amd64.tar.gz"
      sha256 "bed6119abbdf1174c05ee635e3ac4993412615f8120856c8eff639d8da29e8f9"
      define_method(:install) do
        bin.install "dcp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://cli.dcp.nexqloud.net/latest/dcp_1.0.6_linux_arm64.tar.gz"
      sha256 "db92564e84f7d93c6e0dd0e443c5d5222dd23cdd247687bd9e6d9482c2094a91"
      define_method(:install) do
        bin.install "dcp"
      end
    end
  end

  test do
    system "#{bin}/dcp", "--help"
  end
end
