# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dcp < Formula
  desc "Nexqloud DCP CLI"
  homepage "https://nexqloud.io"
  version "1.0.5"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://cli.dcp.nexqloud.net/latest/dcp_1.0.5_darwin_amd64.tar.gz"
      sha256 "3eae46df19942febf76d81b32095dd478083cfb5f9b8546a2fb9edc4c1fbd179"

      define_method(:install) do
        bin.install "dcp"
      end
    end
    if Hardware::CPU.arm?
      url "https://cli.dcp.nexqloud.net/latest/dcp_1.0.5_darwin_arm64.tar.gz"
      sha256 "7900b3ad1a361384a4a4e6bf7b39c64530d16e4f2ef51c11a6496c35e81bbc03"

      define_method(:install) do
        bin.install "dcp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://cli.dcp.nexqloud.net/latest/dcp_1.0.5_linux_amd64.tar.gz"
      sha256 "426ff2bf1602577bea0d595200ed9bed9ddbec18144ff8f58acc06618ea5fb6f"
      define_method(:install) do
        bin.install "dcp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://cli.dcp.nexqloud.net/latest/dcp_1.0.5_linux_arm64.tar.gz"
      sha256 "477e9d973200a878bbc5f294974b488cf4b6595284cdbd1f9788360e02f9433d"
      define_method(:install) do
        bin.install "dcp"
      end
    end
  end

  test do
    system "#{bin}/dcp", "--help"
  end
end
